name: "📝 Lint & Fix Markdown"

on: [push, pull_request]

permissions:
  contents: write

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint & fix Markdown
        uses: github/super-linter@v6
        env:
          VALIDATE_MARKDOWN: true
          FIX_MARKDOWN: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
