name: "🚦 Validate REAL Protocol JSON"

on:
  pull_request:
    paths:
      - 'audit-log.md'
      - 'json-schema.md'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract JSON blocks from audit-log.md
        run: |
          mkdir json_samples
          grep -Poz '(?<=```json\n)[\s\S]*?(?=\n```)' audit-log.md | \
          awk 'BEGIN{RS="\n\n";ORS="\n\n"} {print > "json_samples/sample" NR ".json"}'

      - name: Validate JSON samples
        uses: dsanders11/json-schema-validate-action@v1.4.0
        with:
          schema: './json-schema.md'
          files: 'json_samples/*.json'
